<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Dependencies\Excel\BulkUploadFile.xlsx" />
    <None Remove="Dependencies\Excel\testdoc.xlsx" />
    <None Remove="Dependencies\Excel\UPCsDuplicatedwithinAccount.xlsx" />
    <None Remove="Dependencies\Images\image1.jpg" />
    <None Remove="Dependencies\Images\image2.jpg" />
    <None Remove="Dependencies\Images\NAVIGATOR-LOGO TM.png" />
    <None Remove="Dependencies\PDF\HR1321.pdf" />
    <None Remove="Dependencies\PDF\HR2page.pdf" />
    <None Remove="Dependencies\PDF\page2.pdf" />
    <None Remove="Dependencies\PDF\testdoc.pdf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Dependencies\Excel\BulkUploadFile.xlsx" />
    <EmbeddedResource Include="Dependencies\Excel\testdoc.xlsx" />
    <EmbeddedResource Include="Dependencies\Excel\UPCsDuplicatedwithinAccount.xlsx" />
    <EmbeddedResource Include="Dependencies\Images\image1.jpg" />
    <EmbeddedResource Include="Dependencies\Images\image2.jpg" />
    <EmbeddedResource Include="Dependencies\Images\NAVIGATOR-LOGO TM.png" />
    <EmbeddedResource Include="Dependencies\PDF\HR1321.pdf" />
    <EmbeddedResource Include="Dependencies\PDF\testdoc.pdf" />
  </ItemGroup>

  <ItemGroup>
    <!-- ===== UL.AUTOMATION PACKAGE(S) ===== -->
    
    <PackageReference Include="UL.Automation" Version="5.1.49" />
    <PackageReference Include="UL.Automation.Framework.NUnit" Version="5.1.49" />
    <PackageReference Include="UL.Automation.Reporting.Html" Version="5.1.49" />
    <PackageReference Include="UL.Automation.Reporting.ProgressDialog" Version="5.1.49" />
    <PackageReference Include="UL.Automation.SpecFlow" Version="5.1.49" />
    <PackageReference Include="UL.Automation.SpecFlow.Plugin.NUnit" Version="5.1.49" />
    <PackageReference Include="UL.Automation.TReVor" Version="5.1.49" />
    <PackageReference Include="UL.Automation.Utilities" Version="5.1.49" />
    <PackageReference Include="UL.Automation.Utilities.PDF" Version="5.1.49" />
    <PackageReference Include="UL.Automation.WebDriver" Version="5.1.49" />

    <!-- ===== TREVOR PACKAGE(S) ===== -->

    <PackageReference Include="TReVor.Integrations" Version="3.1.6" />
    <PackageReference Include="TReVor.Integrations.BuildOperations" Version="3.1.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <!-- ===== SPECFLOW PACKAGE(S) ===== -->

    <PackageReference Include="SpecFlow" Version="3.9.74" />
    <PackageReference Include="SpecFlow.NUnit" Version="3.9.74" />
    <PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.9.74" />

    <!-- ===== NUNIT PACKAGE(S) ===== -->

    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <!-- ===== MISC. PACKAGE(S) ===== -->

    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="iTextSharp" Version="5.5.11" />
    <PackageReference Include="Wercs.StyleCop.Settings" Version="3.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\SHA Manager\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="automationSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>