// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UL.Selenium.Portal.RPS.Features.RPSBaseFunctionality_99.RecentActivitiesTab
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Recent Activities - Search")]
    [NUnit.Framework.CategoryAttribute("RPS")]
    [NUnit.Framework.CategoryAttribute("Login")]
    [NUnit.Framework.CategoryAttribute("run_RecentActivites_Search")]
    [NUnit.Framework.CategoryAttribute("LandingPage")]
    [NUnit.Framework.CategoryAttribute("Home")]
    [NUnit.Framework.CategoryAttribute("Shared")]
    [NUnit.Framework.CategoryAttribute("TopBar")]
    [NUnit.Framework.CategoryAttribute("Navigation")]
    [NUnit.Framework.CategoryAttribute("ProductInformation")]
    [NUnit.Framework.CategoryAttribute("ProductLookUP")]
    [NUnit.Framework.CategoryAttribute("Dashboard")]
    [NUnit.Framework.CategoryAttribute("RecentActivities")]
    [NUnit.Framework.CategoryAttribute("RPSSHA")]
    public partial class RecentActivities_SearchFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "RPS",
                "Login",
                "run_RecentActivites_Search",
                "LandingPage",
                "Home",
                "Shared",
                "TopBar",
                "Navigation",
                "ProductInformation",
                "ProductLookUP",
                "Dashboard",
                "RecentActivities",
                "RPSSHA"};
        
#line 1 "Recent Activities - Search.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/RPS Base Functionality - 99/Recent Activities Tab", "Recent Activities - Search", null, ProgrammingLanguage.CSharp, new string[] {
                        "RPS",
                        "Login",
                        "run_RecentActivites_Search",
                        "LandingPage",
                        "Home",
                        "Shared",
                        "TopBar",
                        "Navigation",
                        "ProductInformation",
                        "ProductLookUP",
                        "Dashboard",
                        "RecentActivities",
                        "RPSSHA"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[98614] Base Functionality - Recent Activities - Search for Product ID")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:7001")]
        public virtual void _98614BaseFunctionality_RecentActivities_SearchForProductID()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:7001"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[98614] Base Functionality - Recent Activities - Search for Product ID", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 19
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 20
testRunner.Given("I call Shared Step 104950 (RPS Login - Base functionality) for TReVor account: RP" +
                        "S.99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 21
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 22
testRunner.Given("I click the tab: Recent Activities", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 23
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 24
testRunner.Then("In the recent activities page, I click the label \'Start Date\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 25
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 26
testRunner.And("In the recent activities Page, In the Products table I select a random product an" +
                        "d save product Data to context as: RecentProductData99614", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 27
testRunner.Then("In the recent activities Page, In the Products table I search for the product wit" +
                        "h ID: RecentProductData99614", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 28
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 29
testRunner.Then("In the recent activities Page, In the Products table the first result matches the" +
                        " product ID: RecentProductData99614", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[98615] Base Functionality - Recent Activities - Search for Product Name")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:7002")]
        public virtual void _98615BaseFunctionality_RecentActivities_SearchForProductName()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:7002"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[98615] Base Functionality - Recent Activities - Search for Product Name", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 33
testRunner.Given("I call Shared Step 104950 (RPS Login - Base functionality) for TReVor account: RP" +
                        "S.99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 34
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
testRunner.Given("I click the tab: Recent Activities", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 36
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
testRunner.Then("In the recent activities page, I click the label \'Start Date\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 38
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 39
testRunner.And("In the recent activities Page, In the Products table I select a random product an" +
                        "d save product Data to context as: RecentProductData98615", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 40
testRunner.Then("In the recent activities Page, In the Products table I search for the product wit" +
                        "h Name: RecentProductData98615", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 41
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 42
testRunner.Then("In the recent activities Page, In the Products table the first result matches the" +
                        " product Name: RecentProductData98615", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[98613] Base Functionality - Recent Activities - Search for UPC")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:7003")]
        public virtual void _98613BaseFunctionality_RecentActivities_SearchForUPC()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:7003"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[98613] Base Functionality - Recent Activities - Search for UPC", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 45
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 46
testRunner.Given("I call Shared Step 104950 (RPS Login - Base functionality) for TReVor account: RP" +
                        "S.99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 47
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 48
testRunner.Given("I click the tab: Recent Activities", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 49
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 50
testRunner.Then("In the recent activities page, I click the label \'Start Date\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 51
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 52
testRunner.And("In the recent activities Page, In the Products table I select a random product an" +
                        "d save product Data to context as: RecentProductData98613", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 53
testRunner.Then("In the recent activities Page, In the Products table I search for the product wit" +
                        "h UPC: RecentProductData98613", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 54
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 55
testRunner.Then("In the recent activities Page, In the Products table the first result matches the" +
                        " product ID: RecentProductData98613", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 56
testRunner.Then("In the recent activities Page, In the Products table there is only 1 result showi" +
                        "ng", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 57
testRunner.Then("In the recent activities Page, In the Products table the First result matches the" +
                        " UPCs saved as: RecentProductData98613", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[73171] Base Functionality - Recent Activities - Search for name with comma")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:7006")]
        public virtual void _73171BaseFunctionality_RecentActivities_SearchForNameWithComma()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:7006"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[73171] Base Functionality - Recent Activities - Search for name with comma", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 60
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 61
testRunner.Given("I call Shared Step 104950 (RPS Login - Base functionality) for TReVor account: RP" +
                        "S.99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 62
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 63
testRunner.Given("I click the tab: Recent Activities", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 64
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 65
testRunner.Then("In the recent activities page, I click the label \'Start Date\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 66
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 67
testRunner.Then("In the recent activities Page, In the Products table I search for the product wit" +
                        "h Name: ,", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 68
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 69
testRunner.And("In the recent activities Page, In the Products table I select a random product an" +
                        "d save product Data to context as: RecentProductData73171", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 70
testRunner.Then("In the recent activities Page, In the Products table I search for the Partial Nam" +
                        "e of a comma product saved as: RecentProductData73171", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 71
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 72
testRunner.Then("In the recent activities Page, In the Products table the results contain the prod" +
                        "uct with Name: RecentProductData73171", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[70329] Base Functionality - Recent Activities - Search - Enter Key, or no action" +
            " shows results")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:7011")]
        public virtual void _70329BaseFunctionality_RecentActivities_Search_EnterKeyOrNoActionShowsResults()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:7011"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[70329] Base Functionality - Recent Activities - Search - Enter Key, or no action" +
                    " shows results", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 75
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 76
testRunner.Given("I call Shared Step 104950 (RPS Login - Base functionality) for TReVor account: RP" +
                        "S.99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 77
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 78
testRunner.Given("I click the tab: Recent Activities", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 79
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 80
testRunner.Then("In the recent activities page, I click the label \'Start Date\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 81
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 82
testRunner.Then("In the recent activities Page, In the Products table I search for the product wit" +
                        "h Name: Bath", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 83
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 84
testRunner.Then("In the recent activities Page, In the Products table I confirm that all displayed" +
                        " results contain Bath in their product name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 85
testRunner.And("In the recent activities Page, In the Products table I click the Reset Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 86
testRunner.Then("In the recent activities page, I click the label \'Start Date\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 87
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 88
testRunner.Then("In the recent activities Page, In the Products table I enter name search text: Ba" +
                        "th and press the Enter Key", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 89
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 90
testRunner.Then("In the recent activities Page, In the Products table I confirm that all displayed" +
                        " results contain Bath in their product name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[105064] Base Functionality - Recent Activity - Filter for Product, Filter for ne" +
            "w product - data is refreshed in the product grid")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:7012")]
        public virtual void _105064BaseFunctionality_RecentActivity_FilterForProductFilterForNewProduct_DataIsRefreshedInTheProductGrid()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:7012"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[105064] Base Functionality - Recent Activity - Filter for Product, Filter for ne" +
                    "w product - data is refreshed in the product grid", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 93
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 94
testRunner.Given("I call Shared Step 104950 (RPS Login - Base functionality) for TReVor account: RP" +
                        "S.99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 95
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 96
testRunner.Given("I click the tab: Recent Activities", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 97
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 98
testRunner.Then("In the recent activities page, I click the label \'Start Date\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 99
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 100
testRunner.Then("In the recent activities Page, In the Products table I select 2 random products a" +
                        "nd save product Data to context as: RecentProductData1 and RecentProductData2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 101
testRunner.Then("In the recent activities Page, In the Products table I search for the product wit" +
                        "h ID: RecentProductData1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 102
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 103
testRunner.Then("In the recent activities Page, In the Products table there is only 1 result showi" +
                        "ng", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 104
testRunner.Then("In the recent activities Page, In the Products table the first result matches the" +
                        " product ID: RecentProductData1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 105
testRunner.Then("In the recent activities Page, In the Products table the first result matches the" +
                        " product data: RecentProductData1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 106
testRunner.Then("In the recent activities Page, In the Products table I search for the product wit" +
                        "h ID: RecentProductData2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 107
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 108
testRunner.Then("In the recent activities Page, In the Products table there is only 1 result showi" +
                        "ng", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 109
testRunner.Then("In the recent activities Page, In the Products table the first result matches the" +
                        " product ID: RecentProductData2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 110
testRunner.Then("In the recent activities Page, In the Products table the first result matches the" +
                        " product data: RecentProductData2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 111
testRunner.Then("In the recent activities Page, In the Products table I search for the product wit" +
                        "h ID: RecentProductData1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 112
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 113
testRunner.Then("In the recent activities Page, In the Products table there is only 1 result showi" +
                        "ng", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 114
testRunner.Then("In the recent activities Page, In the Products table the first result matches the" +
                        " product ID: RecentProductData1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 115
testRunner.Then("In the recent activities Page, In the Products table the first result matches the" +
                        " product data: RecentProductData1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
