// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UL.Selenium.Portal.RPS.Features.RPSBaseFunctionality_99.RecentActivitiesTab
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Recent Activities - Breadcrumbs")]
    [NUnit.Framework.CategoryAttribute("RPS")]
    [NUnit.Framework.CategoryAttribute("Login")]
    [NUnit.Framework.CategoryAttribute("run_RecentActivites_Breadcrumbs")]
    [NUnit.Framework.CategoryAttribute("LandingPage")]
    [NUnit.Framework.CategoryAttribute("Home")]
    [NUnit.Framework.CategoryAttribute("Shared")]
    [NUnit.Framework.CategoryAttribute("TopBar")]
    [NUnit.Framework.CategoryAttribute("Navigation")]
    [NUnit.Framework.CategoryAttribute("ProductInformation")]
    [NUnit.Framework.CategoryAttribute("ProductLookUP")]
    [NUnit.Framework.CategoryAttribute("Dashboard")]
    [NUnit.Framework.CategoryAttribute("RecentActivities")]
    [NUnit.Framework.CategoryAttribute("RPSSHA")]
    public partial class RecentActivities_BreadcrumbsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "RPS",
                "Login",
                "run_RecentActivites_Breadcrumbs",
                "LandingPage",
                "Home",
                "Shared",
                "TopBar",
                "Navigation",
                "ProductInformation",
                "ProductLookUP",
                "Dashboard",
                "RecentActivities",
                "RPSSHA"};
        
#line 1 "Recent Activities - Breadcrumbs.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/RPS Base Functionality - 99/Recent Activities Tab", "Recent Activities - Breadcrumbs", null, ProgrammingLanguage.CSharp, new string[] {
                        "RPS",
                        "Login",
                        "run_RecentActivites_Breadcrumbs",
                        "LandingPage",
                        "Home",
                        "Shared",
                        "TopBar",
                        "Navigation",
                        "ProductInformation",
                        "ProductLookUP",
                        "Dashboard",
                        "RecentActivities",
                        "RPSSHA"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[73094] Base Functionality - Recent Activity - Breadcrumbs - Verify Options are t" +
            "he same")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:7090")]
        public virtual void _73094BaseFunctionality_RecentActivity_Breadcrumbs_VerifyOptionsAreTheSame()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:7090"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[73094] Base Functionality - Recent Activity - Breadcrumbs - Verify Options are t" +
                    "he same", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 19
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 20
testRunner.Given("I call Shared Step 104950 (RPS Login - Base functionality) for TReVor account: RP" +
                        "S.99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 21
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 22
testRunner.Given("I click the tab: Recent Activities", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 23
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 24
testRunner.Then("I confirm the Recent Activities page refreshes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 25
testRunner.And("In the recent activities Page, I click the More Filters Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 26
testRunner.Then("In the recent activities Page More Filters Popup, In the Supplier Name field, I e" +
                        "nter: The Dial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 27
testRunner.Then("In the recent activities page, I select the option: Assigned from the status drop" +
                        " down menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 28
testRunner.Then("In the recent activities Page More Filters Popup, I Click the the Apply Filter Bu" +
                        "tton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 29
testRunner.Then("In the recent activities Page, The More Filters Popup is not showing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 30
testRunner.Then("I confirm the Recent Activities page refreshes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 31
testRunner.Then("I confirm that the recent activities page bread crumb area contains the label: Su" +
                        "pplier: \"The Dial\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 32
testRunner.Then("I confirm that the recent activities page bread crumb area contains the label: St" +
                        "atus: \"Assigned\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 33
testRunner.Given("I click the tab: Product Lookup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 34
testRunner.Then("I confirm the Product Lookup tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
testRunner.And("I confirm the active tab is: Product Lookup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table76 = new TechTalk.SpecFlow.Table(new string[] {
                            "Buttons"});
                table76.AddRow(new string[] {
                            "More Filters"});
                table76.AddRow(new string[] {
                            "Reset"});
                table76.AddRow(new string[] {
                            "Export to Excel"});
                table76.AddRow(new string[] {
                            "Select Columns"});
#line 36
testRunner.Then("I confirm that the Product Lookup page buttons to the right of the search box are" +
                        " as follows:", ((string)(null)), table76, "Then ");
#line hidden
#line 42
testRunner.Then("In the Product Lookup Page, I click the More Filters Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 43
testRunner.And("In the Product Lookup Page, The More Filters Popup is showing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 44
testRunner.Then("In the Product Lookup Page More Filters Popup, I click the Supplier Name Filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 45
testRunner.Then("In the Product Lookup Page More Filters Popup, I select the parameter The Dial Co" +
                        "rporation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 46
testRunner.Then("In the Product Lookup Page More Filters Popup, I click the Physical state Filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 47
testRunner.Then("In the Product Lookup Page More Filters Popup, I select the parameter Cream", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 48
testRunner.And("In the Product Lookup Page More Filters Popup, I Click the the OK Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 49
testRunner.Then("In the Product Lookup Page, The More Filters Popup is not showing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 50
testRunner.Then("I confirm that the Lookup Page bread crumb area contains the label: Supplier: \"Th" +
                        "e Dial Corporation\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 51
testRunner.Then("I confirm that the Lookup Page bread crumb area contains the label: Physical stat" +
                        "e: \"Cream\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 52
testRunner.And("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[105035] Base Functionality - Recent Activities - default date range")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:7117")]
        public virtual void _105035BaseFunctionality_RecentActivities_DefaultDateRange()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:7117"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[105035] Base Functionality - Recent Activities - default date range", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 56
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 57
testRunner.Given("I call Shared Step 104950 (RPS Login - Base functionality) for TReVor account: RP" +
                        "S.99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 58
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 59
testRunner.Given("I click the tab: Recent Activities", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 60
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 61
testRunner.And("I confirm that the recent activities page shows the bread crumb area", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 62
testRunner.Then("In the recent activities Page, I confirm the Start Date breadcrumb shows a date 6" +
                        " months before today as default", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 63
testRunner.And("In the recent activities Page, I confirm the End Date breadcrumb shows todays dat" +
                        "e as default", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 64
testRunner.And("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[105018] Base Functionality - Recent Activities - Breadcrumbs")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:7119")]
        public virtual void _105018BaseFunctionality_RecentActivities_Breadcrumbs()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:7119"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[105018] Base Functionality - Recent Activities - Breadcrumbs", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 68
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 69
testRunner.Given("I call Shared Step 104950 (RPS Login - Base functionality) for TReVor account: RP" +
                        "S.99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 70
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 71
testRunner.Given("I click the tab: Recent Activities", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 72
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 73
testRunner.Then("In the recent activities Page, In the Products table I select a random product an" +
                        "d save the supplier name to context as: SavedProduct105018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 74
testRunner.And("In the recent activities Page, I click the More Filters Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 75
testRunner.Then("In the recent activities Page More Filters Popup, In the Supplier Name field, I e" +
                        "nter: SavedProduct105018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 76
testRunner.Then("In the recent activities page, I select the option: New from the status drop down" +
                        " menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 77
testRunner.Then("In the recent activities Page More Filters Popup, I Click the the Apply Filter Bu" +
                        "tton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 78
testRunner.Then("In the recent activities Page, The More Filters Popup is not showing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 79
testRunner.Then("I confirm the Recent Activities page refreshes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 80
testRunner.Then("I confirm that the recent activities page bread crumb area contains the label: Su" +
                        "pplier: \"SavedProduct105018\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 81
testRunner.Then("I confirm that the recent activities page bread crumb area contains the label: St" +
                        "atus: \"New\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 82
testRunner.Then("In the recent activities Page, I confirm the Start Date breadcrumb shows a date 6" +
                        " months before today as default", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 83
testRunner.And("In the recent activities Page, I confirm the End Date breadcrumb shows todays dat" +
                        "e as default", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 84
testRunner.And("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[106837] Base Functionality - Recent Activities - Breadcrumbs - Reset")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:8099")]
        public virtual void _106837BaseFunctionality_RecentActivities_Breadcrumbs_Reset()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:8099"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[106837] Base Functionality - Recent Activities - Breadcrumbs - Reset", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 87
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 88
testRunner.Given("I call Shared Step 104950 (RPS Login - Base functionality) for TReVor account: RP" +
                        "S.99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 89
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 90
testRunner.Given("I click the tab: Recent Activities", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 91
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 92
testRunner.Then("In the recent activities Page, In the Products table I select the first product a" +
                        "nd save the supplier name to context as: SavedProductSupplier106837a", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 93
testRunner.And("In the recent activities Page, In the Products table I select the first product a" +
                        "nd save the status to context as: SavedProductStatus106837a", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 94
testRunner.And("In the recent activities Page, I click the More Filters Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 95
testRunner.And("In the Product Lookup Page, The More Filters Popup is showing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 96
testRunner.Then("In the recent activities Page More Filters Popup, In the Supplier Name field, I e" +
                        "nter: SavedProductSupplier106837a", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 97
testRunner.Then("In the recent activities page, I select the option: SavedProductStatus106837a fro" +
                        "m the status drop down menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 98
testRunner.Then("In the recent activities Page More Filters Popup, I Click the the Apply Filter Bu" +
                        "tton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 99
testRunner.Then("In the recent activities Page, The More Filters Popup is not showing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 100
testRunner.Then("I confirm the Recent Activities page refreshes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 101
testRunner.And("I confirm that the recent activities page shows the bread crumb area", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 102
testRunner.And("In the Recent Activities page, I confirm that the main table shows data rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 103
testRunner.And("In the recent activities Page, In the Products table I confirm that all displayed" +
                        " results contain SavedProductSupplier106837a in their Supplier name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 104
testRunner.Then("In the recent activities Page, In the Products table I confirm that all displayed" +
                        " results show SavedProductStatus106837a as their status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 105
testRunner.Then("I confirm that the recent activities page bread crumb area contains the label: Su" +
                        "pplier: \"SavedProductSupplier106837a\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 106
testRunner.Then("I confirm that the recent activities page bread crumb area contains the label: St" +
                        "atus: \"SavedProductStatus106837a\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 107
testRunner.Then("I confirm that the recent activities page bread crumb area contains the label: Re" +
                        "set", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 108
testRunner.Then("In the recent activities Page, In the Products table I click the Reset Breadcrumb" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 109
testRunner.Then("In the recent activities Page, In the Products table Breadcrumb area only Start D" +
                        "ate and End Date labels are shown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 110
testRunner.And("In the recent activities Page, In the Products table I confirm that not all displ" +
                        "ayed results contain SavedProductSupplier106837a in their Supplier name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 111
testRunner.Then("In the recent activities Page, In the Products table I select the second product " +
                        "and save the supplier name to context as: SavedProductSupplier106837b", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 112
testRunner.And("In the recent activities Page, In the Products table I select the second product " +
                        "and save the status to context as: SavedProductStatus106837b", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 113
testRunner.And("In the recent activities Page, I click the More Filters Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 114
testRunner.And("In the Product Lookup Page, The More Filters Popup is showing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 115
testRunner.Then("In the recent activities Page More Filters Popup, In the Supplier Name field, I e" +
                        "nter part of: SavedProductSupplier106837b and save the partial text as: SavedPro" +
                        "ductSupplier106837bPartial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 116
testRunner.Then("In the recent activities page, I select the option: SavedProductStatus106837b fro" +
                        "m the status drop down menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 117
testRunner.Then("In the recent activities Page More Filters Popup, I Click the the Apply Filter Bu" +
                        "tton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 118
testRunner.Then("In the recent activities Page, The More Filters Popup is not showing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 119
testRunner.Then("I confirm the Recent Activities page refreshes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 120
testRunner.And("I confirm that the recent activities page shows the bread crumb area", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 121
testRunner.And("In the Recent Activities page, I confirm that the main table shows data rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 122
testRunner.Then("I confirm that the recent activities page bread crumb area contains the label: Su" +
                        "pplier: \"SavedProductSupplier106837bPartial\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 123
testRunner.Then("I confirm that the recent activities page bread crumb area contains the label: St" +
                        "atus: \"SavedProductStatus106837b\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 124
testRunner.Then("In the recent activities Page, In the Products table I click the Reset Breadcrumb" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 125
testRunner.And("In the recent activities Page, In the Products table I confirm that not all displ" +
                        "ayed results contain SavedProductSupplier106837bPartial in their Supplier name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 126
testRunner.Then("In the recent activities Page, In the Products table Breadcrumb area only Start D" +
                        "ate and End Date labels are shown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 127
testRunner.And("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[98355] Base Functionality - Recent Activities - Reset button in breadcrumb area " +
            "clears Supplier name")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:8108")]
        public virtual void _98355BaseFunctionality_RecentActivities_ResetButtonInBreadcrumbAreaClearsSupplierName()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:8108"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[98355] Base Functionality - Recent Activities - Reset button in breadcrumb area " +
                    "clears Supplier name", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 131
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 132
testRunner.Given("I call Shared Step 104950 (RPS Login - Base functionality) for TReVor account: RP" +
                        "S.99", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 133
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 134
testRunner.Given("I click the tab: Recent Activities", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 135
testRunner.Then("I confirm the Recent Activities tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 136
testRunner.Then("In the recent activities Page, In the Products table I select a random product an" +
                        "d save the supplier name to context as: SavedProduct98355", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 137
testRunner.And("In the recent activities Page, I click the More Filters Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 138
testRunner.And("In the Product Lookup Page, The More Filters Popup is showing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 139
testRunner.Then("In the recent activities Page More Filters Popup, In the Supplier Name field, I e" +
                        "nter: SavedProduct98355", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 140
testRunner.Then("In the recent activities Page More Filters Popup, I Click the the Apply Filter Bu" +
                        "tton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 141
testRunner.Then("In the recent activities Page, The More Filters Popup is not showing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 142
testRunner.Then("I confirm the Recent Activities page refreshes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 143
testRunner.Then("I confirm that the recent activities page bread crumb area contains the label: Su" +
                        "pplier: \"SavedProduct98355\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 144
testRunner.And("In the recent activities Page, In the Products table I confirm that all displayed" +
                        " results contain SavedProduct98355 in their Supplier name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 145
testRunner.Then("In the recent activities Page, In the Products table I click the Reset Breadcrumb" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 146
testRunner.Then("I confirm that the recent activities page bread crumb area does not contain the l" +
                        "abel: Supplier: \"SavedProduct98355\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 147
testRunner.And("In the recent activities Page, In the Products table I confirm that not all displ" +
                        "ayed results contain SavedProduct98355 in their Supplier name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 148
testRunner.And("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
