// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UL.Selenium.Portal.RPS.Features.ItemSyncWithinRPS
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ItemSync - Manual Entry")]
    [NUnit.Framework.CategoryAttribute("RPS")]
    [NUnit.Framework.CategoryAttribute("Login")]
    [NUnit.Framework.CategoryAttribute("run_ItemSync_Manual_Entry")]
    [NUnit.Framework.CategoryAttribute("LandingPage")]
    [NUnit.Framework.CategoryAttribute("Home")]
    [NUnit.Framework.CategoryAttribute("Shared")]
    [NUnit.Framework.CategoryAttribute("TopBar")]
    [NUnit.Framework.CategoryAttribute("Navigation")]
    [NUnit.Framework.CategoryAttribute("ProductInformation")]
    [NUnit.Framework.CategoryAttribute("ProductLookUP")]
    [NUnit.Framework.CategoryAttribute("Dashboard")]
    [NUnit.Framework.CategoryAttribute("RecentActivities")]
    [NUnit.Framework.CategoryAttribute("RPSSHA")]
    [NUnit.Framework.CategoryAttribute("ItemSync")]
    public partial class ItemSync_ManualEntryFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "RPS",
                "Login",
                "run_ItemSync_Manual_Entry",
                "LandingPage",
                "Home",
                "Shared",
                "TopBar",
                "Navigation",
                "ProductInformation",
                "ProductLookUP",
                "Dashboard",
                "RecentActivities",
                "RPSSHA",
                "ItemSync"};
        
#line 1 "ItemSync - Manual Entry.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/ItemSync Within RPS", "ItemSync - Manual Entry", null, ProgrammingLanguage.CSharp, new string[] {
                        "RPS",
                        "Login",
                        "run_ItemSync_Manual_Entry",
                        "LandingPage",
                        "Home",
                        "Shared",
                        "TopBar",
                        "Navigation",
                        "ProductInformation",
                        "ProductLookUP",
                        "Dashboard",
                        "RecentActivities",
                        "RPSSHA",
                        "ItemSync"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[125705] Base functionality - ItemSync - Manual Entry - Screen layout - initial d" +
            "isplay")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:10388")]
        public virtual void _125705BaseFunctionality_ItemSync_ManualEntry_ScreenLayout_InitialDisplay()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:10388"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[125705] Base functionality - ItemSync - Manual Entry - Screen layout - initial d" +
                    "isplay", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 22
testRunner.Then("I call Shared Step 134359 (RPS Login - User has Standard ItemSync Access)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 23
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 24
testRunner.Given("I click the tab: ItemSync", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 25
testRunner.Then("I click the sub tab: Manual Entry", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 26
testRunner.And("I wait for the ItemSync Manual Entry screen to load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 27
testRunner.Then("I confirm the ItemSync manual entry screen is shown with the title: Add UPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 28
testRunner.Then("In the ItemSync manual entry screen, I see a Text entry field with the default te" +
                        "xt: \'Enter your UPC\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 29
testRunner.Then("In the ItemSync Manual Entry screen, I confirm I see an \'ADD\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 30
testRunner.Given("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[125706] Base functionality - ItemSync - Manual Entry - Invalid UPC entered")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:10397")]
        public virtual void _125706BaseFunctionality_ItemSync_ManualEntry_InvalidUPCEntered()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:10397"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[125706] Base functionality - ItemSync - Manual Entry - Invalid UPC entered", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 33
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 34
testRunner.Then("I call Shared Step 134359 (RPS Login - User has Standard ItemSync Access)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 36
testRunner.Then("I call Shared Step 126165 (RPS - ItemSync - Go to Manual Entry screen)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
testRunner.Then("In the ItemSync Manual Entry screen, I enter: 123456789 into the UPC entry field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 38
testRunner.Then("In the ItemSync Manual Entry screen, I Click the \'ADD\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 39
testRunner.Then("In the ItemSync Manual Entry screen, I confirm the message: Please ensure your UP" +
                        "C is 12 or 14 digits is shown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 40
testRunner.Given("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[125707] Base functionality - ItemSync - Manual Entry - Valid UPC entered - grid " +
            "layout")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:10401")]
        public virtual void _125707BaseFunctionality_ItemSync_ManualEntry_ValidUPCEntered_GridLayout()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:10401"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[125707] Base functionality - ItemSync - Manual Entry - Valid UPC entered - grid " +
                    "layout", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 43
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 44
testRunner.Then("I call Shared Step 134359 (RPS Login - User has Standard ItemSync Access)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 45
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 46
testRunner.Then("I call Shared Step 126165 (RPS - ItemSync - Go to Manual Entry screen)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 47
testRunner.Then("I call Shared Step 125709 (ItemSync - Manual Entry - Add UPC)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 48
testRunner.And("In the ItemSync Manual Entry screenm I confirm I see a UPC Grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 49
testRunner.Then("In the ItemSync Manual Entry screenm I confirm the UPC Grid contains one column a" +
                        "nd its heading is \'UPC\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 50
testRunner.Then("In the ItemSync Manual Entry screen I confirm the UPC Grid contains the UPC: save" +
                        "d as currentRandomUPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 51
testRunner.Then("In the ItemSync Manual Entry screen I confirm that to the right of the UPC: saved" +
                        " as currentRandomUPC I see a \'Remove\' Icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 52
testRunner.Given("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[125710] Base functionality - ItemSync - Manual Entry - Remove valid UPC from UPC" +
            " grid - only 1 UPC present")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:10402")]
        public virtual void _125710BaseFunctionality_ItemSync_ManualEntry_RemoveValidUPCFromUPCGrid_Only1UPCPresent()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:10402"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[125710] Base functionality - ItemSync - Manual Entry - Remove valid UPC from UPC" +
                    " grid - only 1 UPC present", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 55
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 56
testRunner.Then("I call Shared Step 134359 (RPS Login - User has Standard ItemSync Access)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 57
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 58
testRunner.Then("I call Shared Step 126165 (RPS - ItemSync - Go to Manual Entry screen)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 59
testRunner.Then("I call Shared Step 125709 (ItemSync - Manual Entry - Add UPC)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 60
testRunner.Then("In the ItemSync Manual Entry screen I confirm the UPC Grid contains the UPC: save" +
                        "d as currentRandomUPC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 61
testRunner.Then("In the ItemSync Manual Entry screen I confirm that to the right of the UPC: saved" +
                        " as currentRandomUPC I Click the \'Remove\' Icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 62
testRunner.And("In the ItemSync Manual Entry screenm I confirm I do not see a UPC Grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 63
testRunner.Then("In the ItemSync manual entry screen, I see a Text entry field with the default te" +
                        "xt: \'Enter your UPC\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 64
testRunner.Then("In the ItemSync Manual Entry screen, I confirm I see an \'ADD\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 65
testRunner.Given("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[125708] Base functionality - ItemSync - Manual Entry - Remove valid UPC from UPC" +
            " grid - > 1 UPC present")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:10403")]
        public virtual void _125708BaseFunctionality_ItemSync_ManualEntry_RemoveValidUPCFromUPCGrid_1UPCPresent()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:10403"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[125708] Base functionality - ItemSync - Manual Entry - Remove valid UPC from UPC" +
                    " grid - > 1 UPC present", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 68
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 69
testRunner.Then("I call Shared Step 134359 (RPS Login - User has Standard ItemSync Access)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 70
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 71
testRunner.Then("I call Shared Step 126165 (RPS - ItemSync - Go to Manual Entry screen)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 72
testRunner.Then("I generate a random UPC number and save as: UPC125708A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 73
testRunner.Then("I generate a random UPC number and save as: UPC125708B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 74
testRunner.Then("I call Shared Step 125709 (ItemSync - Manual Entry - Add UPC) for UPC: saved as U" +
                        "PC125708A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 75
testRunner.Then("In the ItemSync Manual Entry screen I confirm the UPC Grid contains the UPC: save" +
                        "d as UPC125708A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 76
testRunner.Then("I call Shared Step 125709 (ItemSync - Manual Entry - Add UPC) for UPC: saved as U" +
                        "PC125708B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 77
testRunner.Then("In the ItemSync Manual Entry screen I confirm the UPC Grid contains the UPC: save" +
                        "d as UPC125708B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 78
testRunner.Then("In the ItemSync Manual Entry screen I confirm that to the right of the UPC: saved" +
                        " as UPC125708B I Click the \'Remove\' Icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 79
testRunner.Then("In the ItemSync Manual Entry screen I confirm the UPC Grid does not contain the U" +
                        "PC: saved as UPC125708B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 80
testRunner.Then("In the ItemSync Manual Entry screen I confirm the UPC Grid contains the UPC: save" +
                        "d as UPC125708A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 81
testRunner.Then("In the ItemSync manual entry screen, I see a Text entry field with the default te" +
                        "xt: \'Enter your UPC\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 82
testRunner.Then("In the ItemSync Manual Entry screen, I confirm I see an \'ADD\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 83
testRunner.Given("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[125711] Base functionality - ItemSync - Manual Entry - Valid UPC entered - Uploa" +
            "d Button")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:10404")]
        public virtual void _125711BaseFunctionality_ItemSync_ManualEntry_ValidUPCEntered_UploadButton()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:10404"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[125711] Base functionality - ItemSync - Manual Entry - Valid UPC entered - Uploa" +
                    "d Button", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 87
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 89
testRunner.Then("I call Shared Step 134359 (RPS Login - User has Standard ItemSync Access)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 90
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 91
testRunner.Then("I call Shared Step 126165 (RPS - ItemSync - Go to Manual Entry screen)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 92
testRunner.Then("I call Shared Step 125709 (ItemSync - Manual Entry - Add UPC)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 93
testRunner.And("In the ItemSync Manual Entry screenm I confirm I see a UPC Grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 94
testRunner.Then("In the ItemSync Manual Entry screen, I confirm I see an \'Upload\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 95
testRunner.Given("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[125712] Base functionality - ItemSync - Manual Entry - Upload - \"working\" indica" +
            "tor")]
        [NUnit.Framework.CategoryAttribute("tfs_design")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:10425")]
        public virtual void _125712BaseFunctionality_ItemSync_ManualEntry_Upload_WorkingIndicator()
        {
            string[] tagsOfScenario = new string[] {
                    "tfs_design",
                    "ScenarioId:10425"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[125712] Base functionality - ItemSync - Manual Entry - Upload - \"working\" indica" +
                    "tor", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 99
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 100
testRunner.Then("I call Shared Step 134359 (RPS Login - User has Standard ItemSync Access)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 101
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 102
testRunner.Then("I call Shared Step 126165 (RPS - ItemSync - Go to Manual Entry screen)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 103
testRunner.Then("I generate a random UPC number and save as: UPC125708A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 104
testRunner.Then("I generate a random UPC number and save as: UPC125708B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 105
testRunner.Then("I call Shared Step 126165 (RPS - ItemSync - Go to Manual Entry screen)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 106
testRunner.Then("I call Shared Step 125709 (ItemSync - Manual Entry - Add UPC) for UPC: saved as U" +
                        "PC125708A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 107
testRunner.Then("In the ItemSync Manual Entry screen I confirm the UPC Grid contains the UPC: save" +
                        "d as UPC125708A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 108
testRunner.Then("I call Shared Step 125709 (ItemSync - Manual Entry - Add UPC) for UPC: saved as U" +
                        "PC125708B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 109
testRunner.Then("In the ItemSync Manual Entry screen I confirm the UPC Grid contains the UPC: save" +
                        "d as UPC125708B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 110
testRunner.Then("In the ItemSync Manual Entry screen, I confirm I see an \'Upload\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 111
testRunner.And("In the ItemSync Manual Entry screen, I Click the Upload Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 112
testRunner.Then("In the ItemSync Manual Entry screen, I see the Upload Loading indicator", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 113
testRunner.Given("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[125713] Base functionality - ItemSync - Manual Entry - UPCs Remaining count")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:10426")]
        public virtual void _125713BaseFunctionality_ItemSync_ManualEntry_UPCsRemainingCount()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:10426"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[125713] Base functionality - ItemSync - Manual Entry - UPCs Remaining count", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 116
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 118
testRunner.Then("I call Shared Step 134359 (RPS Login - User has Standard ItemSync Access)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 119
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 120
testRunner.Then("I call Shared Step 126165 (RPS - ItemSync - Go to Manual Entry screen)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 121
testRunner.Then("I generate a random UPC number and save as: UPC125713A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 122
testRunner.Then("I generate a random UPC number and save as: UPC125713B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 123
testRunner.Then("I generate a random UPC number and save as: UPC125713C", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 125
testRunner.Then("I call Shared Step 125709 (ItemSync - Manual Entry - Add UPC) for UPC: saved as U" +
                        "PC125713A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 126
testRunner.Then("In the ItemSync Manual Entry screen, I confirm I see the UPCs remaining count", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 127
testRunner.Then("In the ItemSync Manual Entry screen, I confirm the UPCs Remaining count is shown " +
                        "in the format: xxx UPCs Remaining", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 128
testRunner.And("In the ItemSync Manual Entry screen, I confirm the number shown in the UPCs Remai" +
                        "ning count is: 999", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 129
testRunner.Then("I call Shared Step 125709 (ItemSync - Manual Entry - Add UPC) for UPC: saved as U" +
                        "PC125713B", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 130
testRunner.And("In the ItemSync Manual Entry screen, I confirm the number shown in the UPCs Remai" +
                        "ning count is: 998", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 131
testRunner.Then("I call Shared Step 125709 (ItemSync - Manual Entry - Add UPC) for UPC: saved as U" +
                        "PC125713C", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 132
testRunner.And("In the ItemSync Manual Entry screen, I confirm the number shown in the UPCs Remai" +
                        "ning count is: 997", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 133
testRunner.Then("In the ItemSync Manual Entry screen I confirm that to the right of the UPC: saved" +
                        " as UPC125713B I Click the \'Remove\' Icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 134
testRunner.And("In the ItemSync Manual Entry screen, I confirm the number shown in the UPCs Remai" +
                        "ning count is: 998", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 135
testRunner.Then("In the ItemSync Manual Entry screen I confirm that to the right of the UPC: saved" +
                        " as UPC125713C I Click the \'Remove\' Icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 136
testRunner.And("In the ItemSync Manual Entry screen, I confirm the number shown in the UPCs Remai" +
                        "ning count is: 999", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 137
testRunner.Given("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[126166] Base functionality - ItemSync - Manual Entry - 1,000 Valid UPC entered -" +
            " Add Button greyed out")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:10429")]
        public virtual void _126166BaseFunctionality_ItemSync_ManualEntry_1000ValidUPCEntered_AddButtonGreyedOut()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:10429"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[126166] Base functionality - ItemSync - Manual Entry - 1,000 Valid UPC entered -" +
                    " Add Button greyed out", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 140
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 142
testRunner.Then("I call Shared Step 134359 (RPS Login - User has Standard ItemSync Access)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 143
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 144
testRunner.Then("I call Shared Step 126165 (RPS - ItemSync - Go to Manual Entry screen)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 145
testRunner.Then("I generate 1000 random UPCs save them in a string array as: UPCArray126166", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 146
testRunner.Then("I call Shared Step 125709 (ItemSync - Manual Entry - Add UPC) for UPC: UPCArray12" +
                        "6166", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 147
testRunner.Then("In the ItemSync Manual Entry screen, I confirm the ADD button is greyed out and I" +
                        " cannot add any more UPCs to the grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 148
testRunner.Then("In the ItemSync Manual Entry screen, I confirm I see an \'Upload\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 149
testRunner.And("In the ItemSync Manual Entry screen, I Click the Upload Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 150
testRunner.Then("In the ItemSync Manual Entry screen, I confirm the table footer is showing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 151
testRunner.Given("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[126167] Base functionality - ItemSync - Manual Entry - UPC from UPC grid - scrol" +
            "ling")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:10434")]
        public virtual void _126167BaseFunctionality_ItemSync_ManualEntry_UPCFromUPCGrid_Scrolling()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:10434"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[126167] Base functionality - ItemSync - Manual Entry - UPC from UPC grid - scrol" +
                    "ling", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 155
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 157
testRunner.Then("I call Shared Step 134359 (RPS Login - User has Standard ItemSync Access)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 158
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 159
testRunner.Then("I call Shared Step 126165 (RPS - ItemSync - Go to Manual Entry screen)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 160
testRunner.Then("I generate a total of: 20 random UPCs save them in a string array as: UPCArray126" +
                        "167", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 161
testRunner.Then("I call Shared Step 125709 (ItemSync - Manual Entry - Add UPC) for UPC: UPCArray12" +
                        "6167", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 163
testRunner.Then("In the ItemSync Manual Entry screen, I confirm I can scroll up and down through t" +
                        "he UPC grid List", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 164
testRunner.And("In the ItemSync Manual Entry screen, I confirm the Entry field and the ADD button" +
                        " are still shown at all times while scrolling the UPC grid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 165
testRunner.Given("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("[134935] Base functionality - ItemSync - Manual Entry - Duplicate UPC entered")]
        [NUnit.Framework.CategoryAttribute("ScenarioId:10436")]
        public virtual void _134935BaseFunctionality_ItemSync_ManualEntry_DuplicateUPCEntered()
        {
            string[] tagsOfScenario = new string[] {
                    "ScenarioId:10436"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[134935] Base functionality - ItemSync - Manual Entry - Duplicate UPC entered", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 168
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 170
testRunner.Then("I call Shared Step 134359 (RPS Login - User has Standard ItemSync Access)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 171
testRunner.Then("I confirm the Home tab has loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 172
testRunner.Then("I call Shared Step 126165 (RPS - ItemSync - Go to Manual Entry screen)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 173
testRunner.Then("I generate a random UPC number and save as: UPC126167A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 174
testRunner.Then("I call Shared Step 125709 (ItemSync - Manual Entry - Add UPC) for UPC: saved as U" +
                        "PC126167A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 175
testRunner.Then("I call Shared Step 125709 (ItemSync - Manual Entry - Add UPC) for UPC: saved as U" +
                        "PC126167A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 176
testRunner.Then("In the ItemSync Manual Entry screen, I confirm I see the error with the message U" +
                        "PC already exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 177
testRunner.Then("In the ItemSync Manual Entry screen, I Clear the text in the UPC field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 178
testRunner.Then("In the ItemSync Manual Entry screen, I confirm I do not see the error with the me" +
                        "ssage UPC already exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 179
testRunner.Given("I call Shared Step 106194 (RPS Sign out)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
